# Generated by Django 5.2 on 2025-04-26 18:13

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('model_file', models.FileField(upload_to=api.models.model_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_results', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_type', models.CharField(max_length=20)),
                ('target_column', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('best_model', models.JSONField()),
                ('best_model_name', models.CharField(max_length=100)),
                ('results', models.JSONField()),
                ('feature_names', models.JSONField()),
                ('label_encoder', models.JSONField(null=True)),
                ('X_test', models.JSONField(null=True)),
                ('y_test', models.JSONField(null=True)),
                ('preprocessor', models.BinaryField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
