# Generated by Django 5.2 on 2025-04-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelresult_modeltrainingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresult',
            name='confusion_matrix',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='correlation_matrix',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='feature_importance',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='precision_recall',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='roc_curve',
            field=models.JSONField(null=True),
        ),
    ]
