import { NextResponse } from "next/server"

export async function GET() {
  try {
    // In a real implementation, you would read the precision-recall curve data
    // from a file generated by the Python script

    // For now, we'll return mock data for multiple models
    const prCurveData = {
      models: [
        {
          name: "RandomForest",
          data: Array.from({ length: 100 }, (_, i) => {
            const recall = i / 100
            // Create a curve that shows precision decreasing as recall increases
            const precision = 1 - 0.3 * Math.pow(recall, 1.5)
            return { recall, precision: Math.max(0, precision) }
          }),
          avgPrecision: 0.85,
        },
        {
          name: "LogisticRegression",
          data: Array.from({ length: 100 }, (_, i) => {
            const recall = i / 100
            const precision = 1 - 0.5 * Math.pow(recall, 1.2)
            return { recall, precision: Math.max(0, precision) }
          }),
          avgPrecision: 0.72,
        },
        {
          name: "XGBoost",
          data: Array.from({ length: 100 }, (_, i) => {
            const recall = i / 100
            const precision = 1 - 0.4 * Math.pow(recall, 1.3)
            return { recall, precision: Math.max(0, precision) }
          }),
          avgPrecision: 0.78,
        },
      ],
    }

    return NextResponse.json(prCurveData)
  } catch (error) {
    console.error("Error fetching precision-recall curve data:", error)
    return NextResponse.json({ error: "Failed to fetch precision-recall curve data" }, { status: 500 })
  }
}
