import { NextResponse } from "next/server"

export async function GET() {
  try {
    // In a real implementation, you would read the ROC curve data
    // from a file generated by the Python script

    // For now, we'll return mock data for multiple models
    const rocCurveData = {
      models: [
        {
          name: "RandomForest",
          data: Array.from({ length: 100 }, (_, i) => {
            const x = i / 100
            // Create a curve that's better than random (above the diagonal)
            const y = Math.min(1, x + 0.4 * Math.sin(Math.PI * x))
            return { fpr: x, tpr: y }
          }),
          auc: 0.92,
        },
        {
          name: "LogisticRegression",
          data: Array.from({ length: 100 }, (_, i) => {
            const x = i / 100
            const y = Math.min(1, x + 0.25 * Math.sin(Math.PI * x))
            return { fpr: x, tpr: y }
          }),
          auc: 0.82,
        },
        {
          name: "XGBoost",
          data: Array.from({ length: 100 }, (_, i) => {
            const x = i / 100
            const y = Math.min(1, x + 0.35 * Math.sin(Math.PI * x))
            return { fpr: x, tpr: y }
          }),
          auc: 0.88,
        },
      ],
    }

    return NextResponse.json(rocCurveData)
  } catch (error) {
    console.error("Error fetching ROC curve data:", error)
    return NextResponse.json({ error: "Failed to fetch ROC curve data" }, { status: 500 })
  }
}
